### ISSUE TITLE
invalid class TWEBCHANNEL

### ISSUE THREAD

**Issue by andradevictor** [ricardomansano/webengine_samples#1]
Mansano, bom dia!

Peguei os seus exemplos para "brincar" aqui, porém a classe não está compilada no último RPO da 12.1.17.
Existe algum patch no portal que possui essa classe?

****TOTVS - Build 7.00.131227A - Apr  2 2018
Build Version: 13.2.3.32****

Valeu!

**Comment by danielAlbuquerque** [comment]
+1

**Comment by dougtelles** [comment]
up

**Comment by emersonbn** [comment]
+1

**Comment by ricardomansano** [comment]
Tudo bom Andre?
Confesso que só vi agora tua interação, com certeza vc ja me caçou a respeito disso

**Só pra documentação**
O WebEngine foi disponibilizado apenas pro Lobo Guara, não esta disponível no NG

Abs
