### ISSUE TITLE
Erro WebEngine

### ISSUE THREAD

**Issue by cicerocruz** [ricardomansano/webengine_samples#2]
Mansano, na minha versão ainda não esta funcionando... seria possivel liberar uma atualização somente para  nós brincarmos com a solução em ambiente TESTE?

THREAD ERROR ([2928], SQL01-W7-PDR, SQL-W7-P12-1-3)   16/05/2018 16:33:38
invalid class TWEBCHANNEL on U_ABRESITE(ABRESITE.PRW) 16/05/2018 16:32:26 line : 8

* TOTVS - Build 7.00.131227A - Apr  2 2018 - 16:18:55 NG
* Build: 32 bits
* RPO Format: 32 bits
* SVN Revision: 10707 - 17814 - 1988
* Build Version: 13.2.3.32

**Comment by ricardomansano** [comment]
Tudo bom Cicero?
Confesso que só vi agora tua interação, com certeza vc ja me caçou no grupo a respeito disso

**Só pra documentação**
O WebEngine foi disponibilizado apenas pro Lobo Guara, não esta disponível no NG

Abs
